name: Node.js Package CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MY_GITHUB_TOKEN}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm install

      # - name: Build
      #   run: npm run build # If you have a build script

      - name: Run tests
        run: npm test # If you have tests

      - name: Bump version and Publish to npm
        if: matrix.node-version == '16.x'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push changes
        run: |
          git push origin HEAD:main --tags

      # - name: Push changes to GitHub
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add .
      #     git commit -m "Update from GitHub Actions" || true # This will not fail if there's nothing to commit
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
